name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lockfile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@main
      - name: Update flake.lock
        uses: fym998/update-flake-lock@multi-commit-lock-file-summary
        with:
          flakes: |
            .
            sub-flake/
            sub-flake-empty-commit-summary/
            sub-flake-null-commit-summary/
            sub-flake-not-listed/
          commit-msg: default commit summary message
          commit-msg-per-flake: |
            {
              ".": "Update flake.lock for main flake",
              "sub-flake/": "Update flake.lock for sub-flake",
              "sub-flake-empty-commit-summary/": "",
              "sub-flake-null-commit-summary/": null
            }
